/* GENERATED by scripts/mapcal/emit-ts.mjs — do not edit by hand.
   Source: the hand-drawn map (scripts/mapcal/plan.json), digitised in
   normalized drawing space and verified against the photograph by
   scripts/mapcal/overlay.mjs. Re-run the emitter after editing the plan. */

/* ============================================================
   THE MAP

   One source of truth for where everything on the island is.
   `world-environment.ts` derives the natural geography from this;
   `world.ts` derives the built environment from it; the terrain,
   the ecology, the occupancy registry, the minimap and the race
   all read those.

   Coordinates are metres. The drawing is normalized u,v (0..1,
   left→right and top→bottom); world x = (u − 0.5)·MAP_WIDTH and
   world z = (v − 0.5)·MAP_DEPTH, so +x is east and +z is south and
   the top of the drawing is north.
   ============================================================ */

export const MAP_WIDTH = 266
export const MAP_DEPTH = 199.5

/** Drawing space → world. Kept so the plan can be re-read by hand. */
export function fromDrawing(u: number, v: number): [number, number] {
  return [(u - 0.5) * MAP_WIDTH, (v - 0.5) * MAP_DEPTH]
}
/** World → drawing space. Used by the dev calibration overlay. */
export function toDrawing(x: number, z: number): [number, number] {
  return [x / MAP_WIDTH + 0.5, z / MAP_DEPTH + 0.5]
}

export type Poly = readonly (readonly [number, number])[]

/* ---- the coastline ---------------------------------------- */

/** The island, traced from the drawing's sand/ocean boundary. */
export const ISLAND: Poly = [
  [-99,-87.4], [-79.8,-90.2], [-55.9,-91.8], [-29.3,-92.6], [-2.7,-92.6], [23.9,-91.8],
  [43.9,-90.2], [56.4,-88.2], [61.2,-83.8], [62.2,-77.4], [64.9,-70.6], [69.7,-64.6],
  [76.6,-61], [84.6,-59.8], [92,-61.4], [96.8,-66.2], [99,-72.2], [97.9,-78.6],
  [99.5,-81.8], [103.7,-79], [105.9,-70.6], [107.5,-60.6], [108,-49.9], [108.5,-37.9],
  [109.1,-25.9], [110.1,-14], [111.7,-2], [114.4,10], [117.6,22.3], [120.8,34.3],
  [122.9,45.9], [124,56.7], [122.9,65.8], [118.6,73.4], [110.1,79], [97.4,82.2],
  [81.4,84.2], [62.8,85.4], [42.6,86.2], [20.7,86.6], [-1.6,86.2], [-23.4,85.4],
  [-43.6,83.8], [-62.2,81.4], [-79.3,78.2], [-94.2,73.8], [-106.4,67.8], [-114.9,59.9],
  [-120.2,50.3], [-123.4,38.7], [-125,25.1], [-126.1,10.4], [-126.6,-4.4], [-126.6,-19.2],
  [-125.6,-33.9], [-123.4,-47.5], [-119.2,-60.2], [-112.8,-71.8], [-106.4,-80.6],
]

/** The vegetated islet in the north-east bay. Its own landmass. */
export const ISLET: Poly = [
  [73.3,-78.7], [78.5,-79], [82.9,-76.7], [84.2,-73.1], [82,-69.5], [77.7,-67.9],
  [73.7,-68.8], [72.4,-71.5], [75.5,-72.1], [77.7,-74.4], [75.9,-76.4],
]

/** Every piece of land. `coastInset` is the max over these. */
export const LANDMASSES: readonly Poly[] = [ISLAND, ISLET]

/* ---- the circuit ------------------------------------------ */

/** The racing line, closed, in the direction the drawing's arrows give:
 *  north-west out of the pit straight, anticlockwise round the BLACK
 *  HOLE loop, down the west straight past TNT, east along the south
 *  straight, then the technical section back to the line.
 *  Lap length 633 m. */
export const RACE_LINE: Poly = [
  [-55.9,9], [-61.7,0], [-67.8,-4.4], [-77.1,-6], [-86.4,-5.6], [-89,-9.7],
  [-91.5,-13.8], [-91.8,-19], [-89.6,-24.3], [-87.2,-28.9], [-82.5,-31.9], [-74.5,-33.3],
  [-65.2,-33.9], [-57.2,-34.9], [-50.5,-37.9], [-47.3,-42.9], [-47.1,-49.9], [-47.9,-56.9],
  [-49.2,-63.8], [-50.5,-69.8], [-53.2,-74.8], [-58,-78.2], [-64.4,-80.2], [-71.3,-80.6],
  [-77.9,-79.4], [-83.8,-76.8], [-88.3,-72.8], [-91,-67.8], [-93.1,-61.8], [-95.2,-55.5],
  [-97.6,-49.9], [-100.5,-45.5], [-105.1,-42.9], [-110.4,-41.9], [-113.2,-39.4], [-115.9,-36.9],
  [-116.5,-32.9], [-117,-23.9], [-117.6,-14], [-117.8,-2], [-117.8,10], [-117.6,21.9],
  [-117,33.9], [-116.5,43.9], [-115.7,53.9], [-113.8,61.8], [-110.9,67.2], [-104.8,71.2],
  [-96.3,72.6], [-83,72.8], [-69.2,71.8], [-53.2,71], [-37.2,70.2], [-23.9,69.4],
  [-13.3,68.2], [-4,66.4], [0,64.8], [5.3,59.5], [8,52.9], [8.8,45.9],
  [8.2,38.9], [6.9,31.9], [4.8,24.9], [1.6,18.4], [-2.3,16.5], [-5.9,15.4],
  [-9.1,15.6], [-11.9,16.4], [-14.2,17.8], [-16.1,19.6], [-17.5,21.8], [-18.5,24.2],
  [-18.8,26.9], [-18.7,29.6], [-17,33.5], [-15.4,37.5], [-16.8,42.9], [-19.2,48.3],
  [-22.9,52.7], [-27.9,55.5], [-34,57.1], [-40.4,57.7], [-47.3,57.1], [-51,53.9],
  [-54.4,50.5], [-55.1,46.4], [-55.8,42.3], [-53.2,37.9], [-49.7,32.5], [-47.3,26.5],
  [-47.3,19.9], [-50.5,14.4],
]

/* ---- water ------------------------------------------------ */

/** Lakes are unions of ellipses: the drawing's water is blobby and the
 *  terrain, the water surfaces and the river's lake-discard shader all
 *  want ellipses. Two named bodies, five ellipses. */
export const LAKE_WEST = [
  { x: -82.5, z: 21.9, rx: 13.8, rz: 9.6 },
  { x: -72.9, z: 32.9, rx: 10.6, rz: 11 },
  { x: -79.3, z: 39.9, rx: 12.8, rz: 6.4 },
] as const
export const LAKE_SOUTH = [
  { x: 27.9, z: 37.7, rx: 11.2, rz: 12 },
  { x: 29.8, z: 51.9, rx: 8, rz: 8.4 },
] as const

/** The landing river, crossed by the bridge. */
export const RIVER_LINE: Poly = [
  [4.3,-14], [3.2,-18.8], [9.6,-23.5], [18.1,-27.5], [27.7,-30.7],
  [37.2,-33.5], [44.7,-35.1], [50,-34.7],
]
export const RIVER_WIDTH = 12.8

/* ---- zones ------------------------------------------------ */

export const ZONES = {
  landing: { x: 43.1, z: -7.6, rx: 36, rz: 26 },
  nameLetters: { x: 50.4, z: -14, width: 49.4, depth: 12 },
  bridge: { x: 25.6, z: -30, length: 26.6, width: 9.1, rotation: 0.8 },
  social: { x: -14.1, z: -61.8, rx: 17.6, rz: 14 },
  bowling: { x: 3.2, z: -79, rx: 50, rz: 10.4 },
  bowlingLane: { from: [-39.4, -78.8], to: [1.3, -78.8], width: 11.4 },
  projects: { x: 72.9, z: -47.5, rx: 12.8, rz: 8.4 },
  ramp: { x: 84.6, z: -21.9, length: 30, width: 9.7, rotation: 0 },
  timeMachine: { x: 46, z: 62, radius: 10.6 },
  maze: { x: 79, z: 45, size: 41.8, rotation: 0 },
  achievements: { x: -60.6, z: -17.6, rx: 15.2, rz: 7.4 },
  blackHole: { x: -70, z: -60.2, radius: 12 },
  tnt: { x: -110.1, z: 23.2, rx: 7.4, rz: 12.4 },
  raceStart: { x: -55.9, z: 9 },
} as const

/* ---- vegetation ------------------------------------------- */

export interface VegetationMass {
  id: string
  x: number
  z: number
  rx: number
  rz: number
  /** Relative to 1. The drawing's darker greens are denser. */
  density: number
}

/** The drawing's green masses. Trees and scatter come from these and
 *  nowhere else — there is no island-wide spray. */
export const VEGETATION: VegetationMass[] = [
  { id: 'v1_nw_beach', x: -105.1, z: -64.8, rx: 9.6, rz: 5.6, density: 0.5 },
  { id: 'v2_blackhole_interior', x: -70.5, z: -61.4, rx: 13.8, rz: 12.4, density: 0.7 },
  { id: 'v3_race_infield_north', x: -102.1, z: -25.5, rx: 8, rz: 15.6, density: 0.8 },
  { id: 'v4_north_cluster', x: -39.9, z: -69, rx: 9.6, rz: 7.2, density: 0.7 },
  { id: 'v5_race_social_belt', x: -32.5, z: -42.3, rx: 14.9, rz: 15.6, density: 1 },
  { id: 'v6_start_copse', x: -32.5, z: -5.2, rx: 8.8, rz: 6.8, density: 0.7 },
  { id: 'v7_race_infield_south', x: -66.5, z: 45.1, rx: 39.4, rz: 19.6, density: 0.65 },
  { id: 'v8_hairpin_islet', x: -19.7, z: 32.7, rx: 5.9, rz: 7.6, density: 0.6 },
  { id: 'v10_south_forest', x: 51.9, z: 44.5, rx: 25.3, rz: 22.9, density: 1 },
  { id: 'v11_east_grove', x: 93.1, z: 10, rx: 14.6, rz: 22.9, density: 1 },
  { id: 'v12_bay_island', x: 78.5, z: -73.8, rx: 6.4, rz: 6.4, density: 0.9 },
]

/* ---- paths ------------------------------------------------ */

/** The drawing's brown tracks. Compact earth, not asphalt. */
export const PATHS: { id: string; points: Poly }[] = [
  { id: 'landing_bridge_social', points: [[43.4,1.4], [37.2,-7.6], [30.9,-18], [23.9,-27.5], [16,-37.5], [6.9,-46.3], [-2.1,-53.1], [-6.9,-56.3]] },
  { id: 'social_bowling', points: [[-11.2,-53.1], [-9,-57.5], [-7.4,-61.4], [-5.9,-64.6]] },
  { id: 'bridge_bowling_east', points: [[16,-41.9], [21.8,-48.7], [26.6,-56.7], [33,-62], [40.5,-66.5], [38,-71]] },
  { id: 'bowling_projects', points: [[38,-71], [53.5,-66.5], [59,-61], [63.3,-56], [68.1,-51.1]] },
  { id: 'landing_projects', points: [[43.4,1.4], [53.2,-6], [59.6,-15.2], [63.8,-25.1], [67,-35.1], [69.7,-42.3]] },
  { id: 'landing_ramp', points: [[64.9,-25.5], [71.3,-23.5], [77.7,-22.3]] },
  { id: 'east_coast_road', points: [[70.8,-42.7], [77.7,-37.9], [83,-31.5], [85.7,-23.9], [87.2,-16.4], [89.4,-8.8], [92,-1.2]] },
  { id: 'landing_south_spine', points: [[43.4,1.4], [47.3,12], [49,21.1], [50,30.3], [50.5,39.5], [50,47.5], [49,54], [48,59]] },
  { id: 'landing_maze_road', points: [[53.2,9.2], [60,11], [68,13.5], [74,15.5], [79,18.1]] },
  { id: 'timemachine_maze', points: [[50,60], [48,50], [47,40], [52,26], [54,18], [62,17], [70,17], [79,18.1]] },
  { id: 'landing_racestart', points: [[43.4,1.4], [28.2,0], [12.8,-1.2], [-2.1,-2], [-17,-2.8], [-29.8,-3.2], [-42.6,-3.6], [-51.6,-1.6], [-54.8,0]] },
  { id: 'south_shore_road', points: [[16,71], [29.8,75.4], [42.6,77.8], [54.8,78.2], [64.9,76.2], [69.7,73.8], [70.8,72.2]] },
  { id: 'bowling_west_spur', points: [[-47.3,-73.4], [-48.4,-66.6], [-46.3,-59.5], [-41.5,-52.3], [-35.1,-45.9]] },
]

/* ---- geometry helpers ------------------------------------- */

export function pointInPolygon(x: number, z: number, poly: Poly): boolean {
  let inside = false
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, zi] = poly[i]
    const [xj, zj] = poly[j]
    if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) inside = !inside
  }
  return inside
}

/** Distance to a polygon's edge, unsigned. */
export function polygonEdgeDistance(x: number, z: number, poly: Poly): number {
  let best = Infinity
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [ax, az] = poly[j]
    const [bx, bz] = poly[i]
    const dx = bx - ax
    const dz = bz - az
    const len = dx * dx + dz * dz
    const t = len > 0 ? Math.max(0, Math.min(1, ((x - ax) * dx + (z - az) * dz) / len)) : 0
    const d = Math.hypot(x - ax - dx * t, z - az - dz * t)
    if (d < best) best = d
  }
  return best
}
