import { chromium } from 'playwright'
const b = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader','--use-gl=angle'] })
const p = await (await b.newContext({ viewport: { width: 900, height: 600 } })).newPage()
await p.goto(`${process.argv[2]}/world`, { waitUntil: 'domcontentloaded', timeout: 90000 })
await p.waitForFunction(() => { const x=[...document.querySelectorAll('button')].find(y=>y.textContent?.trim()==='ENTER'); return x && !x.disabled }, { timeout: 120000 })
await p.getByRole('button', { name: 'ENTER', exact: true }).click()
await p.waitForFunction(() => Boolean(window.__world?.vehicle), { timeout: 60000 })
await p.waitForTimeout(2500)
await p.locator('canvas').click({ position: { x: 450, y: 520 } })
const { x, z, rot } = JSON.parse(process.env.AT)
await p.evaluate(({x,z,rot}) => { const g=window.__world; const y=g.terrain.colliderHeightAt(x,z)+2; g.vehicle.moveTo({x,y,z},rot); g.view.focusPoint.trackedPosition.set(x,y,z); g.view.snapToTarget() }, {x,z,rot})
await p.waitForTimeout(1200)
await p.keyboard.down('w')
for (let i = 0; i < 12; i++) {
  await p.waitForTimeout(400)
  const s = await p.evaluate(() => { const g=window.__world; const q=g.player.position; return { x:+q.x.toFixed(1), z:+q.z.toFixed(1), v:+g.vehicle.xzSpeed.toFixed(1), w:g.vehicle.wheels.inContactCount } })
  console.log(`  ${String(i*0.4).padStart(4)}s  (${s.x}, ${s.z})  v=${s.v}  wheels=${s.w}`)
}
await p.keyboard.up('w')
await b.close()
