/**
 * Regenerates CONTENT_STATUS.md from the content data model.
 *   npm run content:status
 *
 * Reads the TypeScript content files through a tiny extraction pass
 * so the report can never drift from the data.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const read = (p) => readFileSync(path.resolve(p), 'utf8')

function extractProjects(src, source) {
  const out = []
  const re = /\{\s*\n\s*id:\s*'([^']+)',/g
  let m
  while ((m = re.exec(src))) {
    const start = m.index
    const end = src.indexOf('\n  },', start)
    const block = src.slice(start, end < 0 ? src.length : end)
    const get = (k) => {
      const r = new RegExp(`${k}:\\s*'([^']*)'`)
      const x = block.match(r)
      return x ? x[1] : ''
    }
    const getBool = (k) => new RegExp(`${k}:\\s*true`).test(block)
    out.push({
      id: m[1],
      title: get('title'),
      importance: get('importance'),
      dataStatus: get('dataStatus'),
      assetStatus: get('assetStatus'),
      motion: get('motionComponent'),
      repository: get('repository') || (get('liveUrl') ? get('liveUrl') : ''),
      privateSource: getBool('privateSource'),
      needsReplacement: getBool('needsReplacement'),
      source,
    })
  }
  return out
}

const personal = extractProjects(read('src/content/projects/personal.ts'), 'GitHub (public)')
const clientSrc = read('src/content/projects/client.ts')
const clientSlugs = [...clientSrc.matchAll(/slug:\s*'([^']+)',\s*title:\s*'([^']+)'/g)]
const clientImportance = [...clientSrc.matchAll(/importance:\s*'([^']+)'/g)].map((m) => m[1])

const client = clientSlugs.map((m, i) => ({
  id: `client-${m[1]}`,
  title: m[2],
  importance: clientImportance[i] ?? 'archive',
  dataStatus: 'verified',
  assetStatus: 'real',
  motion: 'WebsiteMotion',
  repository: 'PRIVATE (Grupo-Newport)',
  privateSource: true,
  needsReplacement: false,
  source: 'Live public website',
}))

const all = [...personal, ...client]

const flag = (v) => (v ? '**yes**' : 'no')
const screenshot = (p) =>
  p.source === 'Live public website' ? 'captured (desktop + mobile, AVIF/WebP)' : 'n/a — procedural motion'

const rows = all
  .sort((a, b) => {
    const order = { hero: 0, featured: 1, archive: 2 }
    return (order[a.importance] ?? 3) - (order[b.importance] ?? 3) || a.title.localeCompare(b.title)
  })
  .map((p) =>
    `| ${p.title} | ${p.source} | ${p.importance} | ${p.dataStatus} | ${p.assetStatus} | ${p.motion} | ${screenshot(p)} | ${flag(p.needsReplacement || p.dataStatus !== 'verified')} |`,
  )

const counts = all.reduce((acc, p) => {
  acc[p.importance] = (acc[p.importance] ?? 0) + 1
  return acc
}, {})

const review = all.filter((p) => p.needsReplacement || p.dataStatus !== 'verified')

const doc = `# Content status

Generated by \`npm run content:status\`. Do not edit by hand — edit the content
files in \`src/content/\` and regenerate.

**${all.length} projects** — ${counts.hero ?? 0} hero, ${counts.featured ?? 0} featured, ${counts.archive ?? 0} archive.
**${all.length - review.length} fully verified**, **${review.length} need manual review**.

## Sources

| Source | Status |
| --- | --- |
| \`Ale-Newport\` public repositories | Audited via the GitHub REST API. READMEs, manifests, file trees and key source files were read; every \`verifiedFacts\` entry and metric below came from one of those. |
| \`Grupo-Newport\` organisation | **All repositories are private and were never accessed.** Client entries are built only from the live public websites (HTTP status, page title, headings, brand colours from public CSS). No source, infrastructure, credentials or client data appear anywhere in this project. |
| CV / stated experience | Roles, dates and outcome metrics for Metaview, Pansofia, KCL and Focus. Marked \`partially-verified\` where the repository could not corroborate them. |

## Projects

| Project | Source | Importance | Data status | Asset status | Motion component | Screenshots | Needs manual review |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

## Needs manual review

${review.length === 0 ? '_Nothing outstanding._' : review.map((p) => `- **${p.title}** — \`dataStatus: ${p.dataStatus}\`, \`assetStatus: ${p.assetStatus}\`.`).join('\n')}

### Specific open items

1. **Gym App** — the repository \`Ale-Newport/Gym-App\` is empty (README only). The chapter is
   built from the described architecture. Replace \`verifiedFacts\` and the exercise count in
   \`src/content/projects/personal.ts\` once the real project is available, and drop a rigged
   \`.glb\` into \`public/assets/models/\` to swap the procedural figure for the real athlete.
2. **Focus** — private source. Description and pipeline are from the stated project scope.
   Add real screenshots or a short capture to \`public/assets/projects/focus/\` and set
   \`assetStatus: 'real'\`.
3. **Catan AI**, **Events App** — repositories exist with no code. Kept in the archive and
   labelled honestly. Remove them or fill them in.
4. **Stock Market Simulator** — the "40,000+ concurrent trades" figure is from the CV; the
   repository configures 4 trader threads at 5 ticks/sec. The metric carries that note in the
   data and is shown with it.
5. **Contact links** — \`email\`, \`linkedin\` and \`cv\` in \`src/content/profile.ts\` are
   marked \`needsVerification: true\`; only the GitHub URL is confirmed. Replace the email and
   LinkedIn values with the real ones. The CV deliberately renders as "On request" rather
   than a link, because the file does not exist yet — drop the PDF at
   \`public/assets/alejandro-newport-cv.pdf\` and set that entry's \`dataStatus\` to \`verified\`
   and it becomes a download with no other change.
6. **Site URL** — \`siteConfig.url\` is a placeholder. Set the real domain before deploying,
   or OpenGraph and the sitemap will point at the wrong host.

## Client websites

All fifteen were verified live (HTTP 200, brand-matching content) and captured with Playwright
at 1440×2200 (desktop) and 390×1400 (iPhone 13), then encoded to AVIF and WebP.
Re-capture at any time with \`npm run capture:clients\`.
`

writeFileSync('CONTENT_STATUS.md', doc)
console.log(`CONTENT_STATUS.md — ${all.length} projects, ${review.length} need review`)
